#!/bin/bash

if [ -z "$1" ]; then
    cat /sys/class/backlight/amdgpu_bl0/brightness
else
	if [[ $1 = "+" ]]; then
		brillo="$( cat /sys/class/backlight/amdgpu_bl0/brightness )"
		inc=$2
		echo $((brillo+inc)) | sudo tee /sys/class/backlight/amdgpu_bl0/brightness
	elif [[ $1 = "-" ]]; then
		brillo="$( cat /sys/class/backlight/amdgpu_bl0/brightness )"
		inc=$2
		echo $((brillo-inc)) | sudo tee /sys/class/backlight/amdgpu_bl0/brightness
	else
		echo $1 | sudo tee /sys/class/backlight/amdgpu_bl0/brightness
	fi
fi
