#!/bin/bash

if [ -z "$1" ]; then
    cat /sys/class/backlight/amdgpu_bl0/brightness
else
	if [[ $1 = "+" ]]; then
		brillo="$( cat /sys/class/backlight/amdgpu_bl0/brightness )"
		inc=$2
		brillo=$((brillo+inc))
		if (( $brillo > 250 )); then
			brillo=250
		fi
		echo $brillo | sudo tee /sys/class/backlight/amdgpu_bl0/brightness
	elif [[ $1 = "-" ]]; then
		brillo="$( cat /sys/class/backlight/amdgpu_bl0/brightness )"
		inc=$2
		brillo=$((brillo-inc))
		if (( $brillo < 0 )); then
			brillo=0
		fi
		echo $brillo | sudo tee /sys/class/backlight/amdgpu_bl0/brightness
	else
		echo $1 | sudo tee /sys/class/backlight/amdgpu_bl0/brightness
	fi
fi
